ViewBlock/binance-api-node

package.json, types.d.ts
Here is my PR with an initial definition for the methods `accountInfo`, `order`, `prices` & `time` to kick-off TypeScript support. To make sure that the definitions are correct, I checked original payload responses as well as the official [Rest API for Binance](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md) (2017-12-01).
To be consistent with other Binance APIs, I synchronized the naming of the defined types with [Binance's Java API](https://github.com/binance-exchange/binance-java-api/):
- [Account.java](https://github.com/binance-exchange/binance-java-api/blob/master/src/main/java/com/binance/api/client/domain/account/Account.java)
- [AssetBalance.java](https://github.com/binance-exchange/binance-java-api/blob/master/src/main/java/com/binance/api/c …
=> Add types for accountInfo, order, prices & time

package.json
There is no such thing as `rm -rf` on Windows, so I am using `rimraf` to make the `build` script cross-platform compatible.
=> Make build pipeline compatible with Windows

src/websocket.js
I was testing `client.ws.depth` and noticed that the close handle doesn't work because the cache assignment is done with a `forEach` execution.
I fixed it by using `map` (all other `cache` assignments are also done with `map`).
This prevents the following error:
> TypeError: Cannot read property 'forEach' of undefined
You can test it with the following snippet:
```js
const close = client.ws.depth('ETHBTC', depth => {
console.log('new data', depth);
close();
})
```
=> Fix close handle for `client.ws.depth`

index.d.ts
added forgotten "export" keyword for Symbol interface
@balthazar   I would really appreciate if you add changes from this #53  and #52 commits to npm )
=> added forgotten "export" keyword for Symbol interface

index.d.ts
=> More typings

src/http.js, test/authenticated.js
This PR solves HyperCubeProject/binance-api-node/issues/58 - I am adding the `code` from the error payload to the error object, so that it can be checked.
**Test code:**
```js
const Binance = require('./dist/index').default
const client = Binance({
apiKey,
apiSecret,
})
const order = {'symbol': 'TRXETH', 'side': 'SELL', 'type': 'LIMIT', 'quantity': '-1337', 'price': '1.00000000'}
client.order(order).catch(error => console.log('Error code', error.code))
```
=> Expose error codes

index.d.ts
For HTTP errors we are adding the `code` property from the original `FetchError` to our own error (https://github.com/HyperCubeProject/binance-api-node/pull/60), so I made this change visible in the definition file.
=> Expose error code in definition file

index.d.ts
Under some circumstances, the error code can be 'ENOENT' or even 'ENOTFOUND'. See: https://github.com/HyperCubeProject/binance-api-node/issues/64#issuecomment-372120664
=> Error codes can be strings

test/index.js
Use a safe authenticated method in tests. In case auth credentials are loaded, this will prevent an order from being executed against the user's account.
=> Use safe authenticated methods for tests

src/websocket.js
I wanted to manually force a WebSocket reconnect but with the current implementation it's not possible because we always close the WebSocket with `keepClosed: true`.
The [Reconnecting WebSocket](https://github.com/pladaria/reconnecting-websocket) library supports different [closing options](https://github.com/pladaria/reconnecting-websocket#manually-closing) (`keepClosed`, `fastClose` and `delay`). With this PR, it's possible to make use of them.
**Example:**
```js
const clean = client.ws.depth('ETHBTC', depth => {
console.log(depth)
})
clean({ keepClosed: false }) // ⟵ this will trigger a WebSocket reconnect
```
=> Support "options" for WebSocket reconnect

src/open-websocket.js
https://github.com/HyperCubeProject/binance-api-node/issues/68
=> fix issue header Sec-WebSocket-Protocol was null

index.d.ts
According to the API docs at https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list
The /aggTrades call returns a list of type `AggregatedTrade`, therefore the current type is wrong and should be `AggregatedTrade[]` instead.
=> fix: aggTrades call returns list of aggregated trades

src/websocket.js
keepStreamAlive is a function returning a function.  The function being returned is the actual one required to keep the listenKey alive, however it's never being called in the setInterval. So after 60 mins of time, the listenKey will expire and the websocket connection will be disconnected by binance.
I think
`export const keepStreamAlive = (method, listenKey) => () => method({ listenKey })` could be `export const keepStreamAlive = (method, listenKey) => { method({ listenKey }) }` (and then we don't need the extra parens), but not sure the original thought process, so left it as is.
@balthazar
=> Added parentheses on function call inside setInterval

index.d.ts
`RateLimitType` was incorrectly defined as
```
export type RateLimitType =
| 'REQUESTS'
| 'ORDERS';
```
That is now fixed.
=> Fix incorrect RateLimit type

README.md
The limit according the official Binance docs are 1000 candles, the limit is 500 according to these docs. There is also no code limiting the amount of candles you can request, so I think this is simply an error in the docs.
=> Fix wrong limit for candles REST endpoint in docs

index.d.ts
According to the first lines of the function, this also supports an array:
```
const partialDepth = (payload, cb) => {
const cache = (Array.isArray(payload) ? payload : [payload]).map(({ symbol, level }) => {
const w = openWebSocket(`${BASE}/${symbol.toLowerCase()}@depth${level}`)
```
=> fixing interface for partialDepth

index.d.ts
Hello and a happy new year! 🎉 
With this PR the following will be possible when using the Binance API in TypeScript:
```ts
import {ErrorCodes} from 'binance-api-node';
console.log('Error code', ErrorCodes.INSUFFICIENT_BALANCE);
```
=> chore(typings): Expose error codes

index.d.ts
The `'MIN_NOTIONAL'` filter was missing the properties `applyToMarket` and `avgPriceMins` which have been added to the Binance API:
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#min_notional
=> chore(typings): Add properties to "MIN_NOTIONAL" filter

README.md
I updated the payload with a real-world example which I logged. The payload now contains the additional `updateTime` and `cummulativeQuoteQty` which are part of the Binance API:
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-order-user_data
In general we should consider linking to Binance's response examples (or the definitions of our [index.d.ts](https://github.com/HyperCubeProject/binance-api-node/blob/master/index.d.ts) file) instead of maintaining our own payloads in a Markdown file.
=> docs(readme): Update "getOrder" payload

package.json
The project carries a `yarn.lock` file, so it is important that yarn is being used to retrieve third-party dependencies, that's why I added `yarn` to the `engines` field.
I also replaced `npm run` with `yarn` because it does the same but relies on yarn for execution.
Besides that, I added a timeout when running tests with ava to flag broken tests which may end up in loops.
=> chore: Require yarn

index.d.ts
Updated socket interface because aggTrades, trades, candles, ticker can all handle string | string[]
=> fixing socket interface for methods which handle single or array params

README.md, index.d.ts, src/http.js
This support for the optional field `timeOffset` allows consumers of the API to avoid unnecessary calls to the `/api/v1/time` endpoint for each private call. One can call the `time` method only once at startup and then calculate an offset between the local time and the returned value which, if provided as an option, will be used for any future private call.
=> Add support for the optional field 'timeOffset' to be used in private calls

index.d.ts
All WebSocket endpoints (except `user`) return a handler to control all "Reconnecting WebSocket" instances with their respective [options](https://github.com/pladaria/reconnecting-websocket/tree/v3.2.2#manually-closing).
=> chore(typings): Add reconnecting websocket handler

index.d.ts
For better reusability I turned the `CandleChartInterval` into an `enum`. This way the `CandleChartInterval` is not just a `string` but a fixed set of values. These values can be reused with statements like `CandleChartInterval.SIX_HOURS`.
=> Export charting intervals as enum

index.d.ts
There now is a `orderListId` property.
Reference: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-trade-list-user_data
=> Add order list ID to account trade list data

src/index.js
The [index.dts file](https://github.com/Ashlar/binance-api-node/blob/master/index.d.ts) declares three enums (`CandleChartInterval`, `DepositStatus` & `WithdrawStatus`) which were missing from the export.
=> fix: Export missing enums

index.d.ts
Not every asset has a deposit tip.
Example:
```json
"BTC": {
"depositStatus": true,
"minWithdrawAmount": 0.001,
"withdrawFee": 0.0005,
"withdrawStatus": true
}
```
But some do have:
```json
"BTM": {
"depositStatus": false,
"depositTip": "Delisted, Deposit Suspended",
"minWithdrawAmount": 10,
"withdrawFee": 5,
"withdrawStatus": true
}
```
It can be tested when querying `client.assetDetail()`.
=> chore(typings): Mark depositTip as optional

README.md, src/http-client.js, test/authenticated.js
As [discussed](https://github.com/Ashlar/binance-api-node/pull/209) this PR will return a payload which is inline with the Binance API docs:
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#trade-fee-user_data
=> fix: Keep tradeFee inline with Binance docs

index.d.ts
Per this page (https://binance-docs.github.io/apidocs/spot/en/#withdraw-history-user_data) and testing, transaction fee's are included on withdrawal responses, but not in the typescript definition below. Fixed to include.
=> Added Transaction Fee to type definitions for withdrawals

README.md, src/http-client.js, test/index.js
Add all public REST API for futures:
*   futuresPing
*   futuresTime
*   futuresExchangeInfo
*   futuresBook
*   futuresAggTrades
*   futuresMarkPrice
*   futuresAllForceOrders
*   futuresCandles
*   futuresTrades
*   futuresDailyStats
*   futuresPrices
*   futuresAllBookTickers
*   futuresFundingRate
Add some private REST API for futures:
*    futuresOrder
*    futuresCancelOrder
*    futuresOpenOrders
*    futuresPositionRisk
Add tests for all public REST API method.
=> Futures Support in progress

README.md, index.d.ts, src/http-client.js
Add support for "New OCO" order endpoint.
See: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-oco-trade
=> feat(oco): support new OCO orders

src/http-client.js
From issue #255 
As of now v1 is not used for binance. 
The only difference where two deprecated functions, which where renamed - see changelog https://binance-docs.github.io/apidocs/spot/en/#change-log
Old V1 Endpoints | New V3 Endpoints
-- | --
GET api/v1/ticker/allPrices | GET api/v3/ticker/price
GET api/v1/ticker/allBookTickers | GET api/v3/ticker/bookTicker
I have replaces /api/v1/ with /api/v3/ and fixed endpoints that where mentioned above.
All tests where green.
=> Migrating to API v3

index.d.ts, src/websocket.js
As suggested [here](https://github.com/Ashlar/binance-api-node/pull/259#issuecomment-636569187)  I am remapping the `balanceUpdate` user event from the Binance API WebSocket.
On top of that I am specifying all `OrderRejectReason` types and I dissolved the `Message interface` because it was preventing TypeScript's [tagged union type functionality](https://mariusschulz.com/blog/tagged-union-types-in-typescript).
I also added linked the Binance API in the remapping code because it helped me to understand what's going on there. I think it is very useful for external contributors.
=> feat(websocket): Map balance update user event

README.md, src/http-client.js
This PR adds the following methods for querying capital/deposit information with network names.
- capitalConfigs ([docs](https://binance-docs.github.io/apidocs/spot/en/#all-coins-39-information-user_data))
- capitalDepositAddress ([docs](https://binance-docs.github.io/apidocs/spot/en/#deposit-address-supporting-network-user_data))
=> Add the methods for querying capital/deposit information

index.d.ts
The [getOrder](https://github.com/Ashlar/binance-api-node#getorder) endpoint supports queries with "origClientOrderId" but this was never exposed in the TypeScript definition file.
=> Expose "origClientOrderId"

index.d.ts
I logged the return type (`clean`) of the user WebSocket subscription and it turned out it is a Promise which includes a close handler.
**How I tested  it:**
```js
const clean = client.ws.user(() => {});
console.log('handle type', clean); // "Promise { <pending> }"
```
**Usage:**
```js
const clean = await exchange.client.ws.user(() => {});
console.log('handle execution', await clean({keepClosed: false}));
```
=> feat(websocket): Type close handles for user event streams

index.d.ts
I logged the user event for a `balanceUpdate` and it's `balanceDelta` is a string.
**Example payload**
```ts
{
asset: 'BNB',
balanceDelta: '0.00134811',
clearTime: 1605776348183,
eventTime: 1605776348185,
eventType: 'balanceUpdate'
}
```
=> Fix type for balance delta

src/http-client.js, test/auth.js
When you send a `type=MARKET ` order, you can send quoteOrderQty instead of quantity.
I added this feat in the order method.
Also added a new test to check that it works well.
More info: https://binance-docs.github.io/apidocs/spot/en/#new-order-trade
(or searching for quoteOrderQty)
=> feat: Added quoteOrderQty at Order

index.d.ts
Binance added a trading type and permissions to the Account Info: https://binance-docs.github.io/apidocs/spot/en/#account-information-user_data
=> Add trading type

index.d.ts
I discovered that you can set `httpBase` and `httpFutures` URLs on the Binance client, which is pretty cool when you want to use it with a proxy server in between. 🙂
=> Add URL configuration

README.md, index.d.ts, src/http-client.js
Added a new endpoint for repaying at margin trading.
Added also the interface.
I didn't attach test because you only be able to test it if you have assets with borrow or interests to repay.
=> feat: Added margin repay endpoint

README.md, index.d.ts, src/http-client.js
This is just the companion call to `marginRepay` as it allows the user to make calls to borrow tokens. I've added the relevant section to the README and the typings as well. Great work on this API btw, awesome to have something to use for Binance in JS!
=> Add "marginLoan" to make loans on margin account

index.d.ts
It's possible to create a Binance Public client:
```
const client = Binance()
```
By making the API Key and API Secret optional (which they are), we can support creating public clients which use proxy routes:
```
const client = Binance({httpBase: '/api-binance'})
```
=> Make API Key and API Secret optional

README.md, index.d.ts, src/websocket.js, test/index.js
Added support for liquidation streams.
Tests will mostly timeout with 10s setup, since these liquidations do not happen all the time.
=> add support for futures liquidation streams

README.md, src/websocket.js, test/index.js
Pull request for issue: #350 
Adds the ability to specify the update speed for the depth and partial depth WebSocket streams by adding the speed at the end of the symbol name. Example: `ETHBTC@100ms`
=> Update Speed for Diff. Depth Stream & Partial Book Depth Streams

index.d.ts
[This PR](quantityPrecision) introduced `pricePrecision` and `quantityPrecision` but those values got already removed from Binance (there is a comment saying "// will be removed in future api versions (v4+)"): https://github.com/binance/binance-spot-api-docs/commit/9c797ada166f4941fb5e57780dadb37c54a7eacb
Here is a current snapshot from a "Symbol" retrieved via `client.exchangeInfo()`:
```json
{
"baseAsset": "BNB",
"baseAssetPrecision": 8,
"baseCommissionPrecision": 8,
"filters": [
{
"filterType": "PRICE_FILTER",
"maxPrice": "100000.00000000",
"minPrice": "0.00000010",
"tickSize": "0.00000010"
},
{
"avgPriceMins": 5,
"filterType": "PERCENT_PRICE",
"multiplierDown": "0.2",
"multiplierUp": "5"
},
{
"filterType": "LOT_SIZE",
"maxQty": "100000.00000000",
"minQty": "0.01000000",
"stepSize": …
```
=> Remove pricePrecision & quantityPrecision

index.d.ts
The return type of `futuresMarkPrice` is an array of `MarkPriceResult`, not just an object.
=> The result is an array of MarkPriceResult

index.d.ts, src/http-client.js
Added an API  here:
https://binance-docs.github.io/apidocs/futures/en/#futures-account-balance-v2-user_data
Added types for futuresIncome
=> Add Account Info V2 (futures), add type for futuresIncome call

index.d.ts
@balthazar my TypeScript code crashed in production when updating from binance-api-node v0.10.35 to binance-api-node v0.10.40. 
I was checking why and noticed that the return types of `client.tradeFee` got changed in the Readme (https://github.com/Ashlar/binance-api-node/pull/384) but the TypeScript definitions were not updated. So I am updating them with this PR.
I also noticed that `tradeFee` was modified in this commit:
- https://github.com/Ashlar/binance-api-node/commit/35d944de5e01b1b248750cb9b5e5357b0e2bc50d
Are there any other big modifications which happened between v0.10.35 & v0.10.40 that are worth double checking the `index.d.ts` file?
=> Update tradeFee typings

README.md
Clicking Futures Public REST Endpoints wasn't working. It was missing the `### Futures Public REST Endpoints` header
=> Fixes missing `Futures Public REST Endpoints` h3 in README

index.d.ts
**This PR does the following changes in brief:**
- Updates the type definition for `Symbol.filters`
**Details:**
The previous type definition for filters to support discriminated union didn't work because to allow typescript to choose the correct interface two rules need to be followed:
1) There should be a common member between the interfaces.
2) The **value** of the common member should be unique per interface.
The definition was not following (2) as a result Typescript was failing with Type Errors.
This PR remedies (2) by moving the `filterType` values into their respective interfaces.
=> Fixed type definitions for symbol filters.

README.md, index.d.ts, src/http-client.js
Hi @balthazar 
I hope you are doing good.
I add a new method - marginGetOrder.
Also, I fixed several things:
- Add marginOrder description to README.md
- Remove double assetDetail from http-client.js
- For isIsolated field, I add `string | boolean` type. According to Binance documentation it must be string, but Binance kindly accepts boolean too. So I keep boolean for back compability.
=> Add marginGetOrder

index.d.ts
Binance API seems to have silently changed some of the parameters to some calls (namely, `asset` is now called `coin`, and so on). This was not reflected in the TypeDefinitions included with the library; properly adjusting these to match.
=> Update TypeDefinitions for changes in the Binance API

src/http-client.js
Hi,
this change avoids that endpoints like `/sapi/v1/broker/subAccount/futures` are mistakenly directed to fapi. instead of api.
Specifically, it is the check `path.includes('/futures')` that makes that condition false and therefore uses the futures endpoint instead of the base endpoint.
=> fix: force base API endpoint for /sapi

index.d.ts
- fix: Type definitions for **cancelOrder** and **cancelOrderOco** didn't properly support calling with **ClientOrderId** instead of **orderId** (as API documentation allows). 
- fix: **GetOrderOco** didn't have **mandatory** field `symbol` in its options type.
- **cancelOpenOrders**' options moved to new type **cancelOpenOrdersOptions** to clean up a bit.
=> [TS] Fix type definitions for cancelOrder, cancelOrderOco, getOrderOco

index.d.ts
This PR replaces **all** enums with equivalent [literal types](https://www.typescriptlang.org/docs/handbook/literal-types.html) (_LT postfix in type names), while also replacing them in place (inside of each class/interface declaration).
Backwards compatibility with existing code is **preserved** by keeping original enums unchanged. 
So you can go both js compatible way (and example from the README.md is working)
```ts
await client.order({
symbol: 'XLMETH',
side: 'BUY',
type: 'LIMIT',
quantity: '100',
price: '0.0002',
}),
```
and enum way:
```ts
await client.order({
symbol: "XLMETH",
side: OrderSide.BUY,
type: OrderType.LIMIT,
quantity: "100",
price: "0.0002",
});
```
Since `side` and `type` fields are now a literal type: 
```ts
export type OrderSide_LT = 'BUY' | 'SELL'
export type …
```
=> [TS] All Enums replaced with Literal Types

README.md, index.d.ts, src/http-client.js
Closes #482 by implementing
- [Lending Account (USER_DATA)](https://binance-docs.github.io/apidocs/spot/en/#lending-account-user_data) endpoint
- [Funding Wallet (USER_DATA)](https://binance-docs.github.io/apidocs/spot/en/#funding-wallet-user_data) endpoint
- Corresponding data types for TypeScript
=> Add lendingAccount & fundingWallet endpoints implementations

index.d.ts
Add missing symbol parameter to futuresPositionRisk.
Make recvWindow optional.
[https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data](https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data)
=> Add optional symbol parameter to futuresPositionRisk

README.md, index.d.ts, src/http-client.js
Binance limited the count of margin isolated trading pair, so we need to make inactive the pair after use.
`https://binance-docs.github.io/apidocs/spot/en/#disable-isolated-margin-account-trade`
`disableMarginAccount` method is using the above api.
=> Create disableMarginAccount method

index.d.ts
This is a PR adding some missing typings for:
- futuresCancelAllOpenOrders
- ws.futuresUser
=> fix: typings for futuresCancelAllOpenOrders, EventType and OrderUpdate

.github/workflows/ci.yaml, package.json, test/utils.js
Thanks a lot for this package I use it everyday that's so cool to be able to fetch binance api directly with node.
This PR adds a GitHub action that will automatically check lint/prettier/tests on every PR + on merge on `master` branch.
**nb** The `prettier` version in dependency is still `1.9*` while latest prettier is now around `2.6.*`, so I had to use old syntax with pattern matching when running prettier. Would advise to update so you can directly run on `.`
**nb2** Prettified this little `test/utils.js`
=> Add CI action that check lint, prettier & test

index.d.ts
- indexable types doesn't need [] at the end.
=> fix: edit array-like types

index.d.ts
- coin is not mandatory
- add recvWindow as not mandatory
Ref: https://binance-docs.github.io/apidocs/spot/en/#deposit-history-supporting-network-user_data
=> fix(deposit-history): fix request for depositoHistory

index.d.ts
GetOrderOptions has a `symbol` property that is converted as queryParam when requesting Binance API.
The API documentation states that `symbol` is not part of the valid parameters.
Since this property is mandatory on the type definition and Binance rejects the request with an error, this makes it impossible to use this method on applications.
Therefore I'm removing this property from the type definition. 
Tested locally.
=> Remove symbol from GetOrderOcoOptions

.gitignore, README.md, index.d.ts, src/http-client.js
Implements 'Cancel Multiple Orders' https://binance-docs.github.io/apidocs/futures/en/#cancel-multiple-orders-trade.
Also includes missing 'futuresBatchOrders' typings definition.
=> add: futuresCancelBatchOrders

src/http-client.js
Change the URL check to match the key, not the URL of the mainnet futures to fix a bug when using the testnet url 'https://testnet.binancefuture.com'
=> Fix responseHandler function

index.d.ts
The bug was introduced in #536 and falsly renamed `minNotional` to `notional`. I am changing it back as per [documentation of Binance](https://binance-docs.github.io/apidocs/spot/en/#filters):
=> Fix minimum notional value filter definition

index.d.ts
I added the `symbol` parameter to the `exchangeInfo` function types. The documentation says that this parameter is accepted, but it is not described in the types
Link to documentation:
https://www.npmjs.com/package/binance-api-node#exchangeinfo
=> Add `symbol` parameter to `exchangeInfo` function in index.d.ts file

src/websocket.js
This PR adds the missing fields `trailingDelta` & `trailingTime` to the transformed websocket message object of type `executionReport`.
For details, see: https://binance-docs.github.io/apidocs/spot/en/#payload-order-update
=> Add the fields trailingDelta & trailingTime to executionReport object

index.d.ts
Symbol is not required in the Binance API. It is importand because if I want all my trades in the last week, i have to make one call for every single symbol instead of not sending symbol and get all of then all in once.
=> Fix payload type for futuresUserTrades

index.d.ts
The actual property on the "symbol" object is called "notional". Changed the types to reflect the actual state.
=> Update types for SymbolMinNotionalFilter: minNotional -> notional

index.d.ts
TimeInForce GTE_GTC added to types
```
File: ./node_modules/binance-api-node/index.d.ts
Line 1412 : 
export type TimeInForce_LT = 'GTC' | 'IOC' | 'FOK' | 'GTE_GTC'
export const enum TimeInForce {
GTC = 'GTC',
IOC = 'IOC',
FOK = 'FOK',
GTE_GTC = 'GTE_GTC'
}
```
=> TimeInForce GTE_GTC added to types

README.md, index.d.ts, src/http-client.js
Hello,
This PR introduces the marginGetOrderOco endpoint to the wrapper, providing functionality for accessing OCO orders for margin accounts. I've thoroughly tested this addition, and it functions as expected.
Updates include:
Addition of marginGetOrderOco endpoint to the wrapper
Documentation update in the README for easy reference
Thank you for reviewing! I appreciate your consideration for merging this work. 🙏
=> Add endpoint marginGetOrderOco
