- index.d.ts
Related to #50
Added firstUpdateId and finalUpdateId properties to Depth interface  to **index.d.ts**
> index.d.ts - necessary changes that were missed in release 0.5.7

- index.d.ts
Added Candlestick chart intervals: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#klinecandlestick-streams
> Added Candlestick chart intervals

- test/authenticated.js
- test/index.js
- test/websocket-reconnect.js
Parallelize tests for shorter build times.
> Parallelize tests

- index.d.ts
Adding type definitions to the `candles` (REST) method.
> Typed candles

- index.d.ts
> Support string arrays for "depth"

- index.d.ts
> chore(typings): expose allBookTickers method via typings

- src/websocket.js
Info:
Corrected setInterval call.
Need to wrap function with arguments in anonymous function (or arrow function) otherwise it'll never get called. After 60 mins, you'll get a `This listenKey does not exist` error.
Original PR (https://github.com/binance-exchange/binance-api-node/pull/12) move to this repo.
> Wrap around anonymous function otherwise keepStreamAlive never called

- index.d.ts
Had wrong interface defined for tradeFee. Fixed now. Sorry for hassle.
> fix interface

- README.md
- index.d.ts
- src/http.js
- test/index.js
> Add avgPrice endPoint

- package.json
This command will be executed when the dependency is fetched from Git: https://docs.npmjs.com/misc/scripts
> adding prepare command to install directly from git

- index.d.ts
make symbol optional: get all open orders, but keep useServerTime: true
> make symbol optional

- index.d.ts
add allOrders type definitions.
> add allOrders type definitions.

- README.md
- index.d.ts
Sample payload for `rateLimits` is:
```json
"rateLimits": [
{
"rateLimitType": "REQUEST_WEIGHT",
"interval": "MINUTE",
"intervalNum": 1,
"limit": 1200
},
{
"rateLimitType": "ORDERS",
"interval": "SECOND",
"intervalNum": 1,
"limit": 10
},
{
"rateLimitType": "ORDERS",
"interval": "DAY",
"intervalNum": 1,
"limit": 100000
}
]
```
> chore(typings): Add "intervalNum" property

- index.d.ts
Add `newOrderRespType` property to `NewOrder` interface.
See: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade
> chore(typings): Add `newOrderRespType` property

- index.d.ts
Add typings for `PERCENT_PRICE` filter.
See: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#percent_price
> chore(typings): Add `PERCENT_PRICE` filter

- index.d.ts
See - https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#account-trade-list-user_data
> Added quoteQty to MyTrade interface

- index.d.ts
Hi there,
I noticed this field totalQuoteTradeQuantity was missing and I wonder if it's related to this issue?
#184 
Cheers
> missing field totalQuoteTradeQuantity

- README.md
- src/http-client.js
- src/websocket.js
see https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md
> provide Binance margin websocket stream and basic margin trading endpoints support

- index.d.ts
> add marginUser to typings

- src/http-client.js
wanted to add futures endpoints+websocket but notices they use a different hostname.
- added new host name for futures rest
- refactor the hack to preappend "/api" its now moved to where is needed
- provide new api publicRequest and privateRequest for allow calling not supported APIs, i noticed the binance team is really fast adding new endpoints this allows the usage here with provide the public method at all.
Will also add the websocket support for futures after this merge, but needs some more key and connection handling is the same, but parameters are a little bit different
> move all path urls inside calls itself and prepare futures endpoint; also usage of unmanaged public / private calls

- index.d.ts
New properties have been added to `/api/v3/exchangeInfo`:
- https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information
> feat: Add new properties to Symbols

- README.md
- index.d.ts
Fixes issue: https://github.com/Ashlar/binance-api-node/issues/239
This PR also includes types for futures methods.
Thoughts? The accuracy of the methods as they are currently implemented is not 100%. This PR doesn't fix that, and updating all the types is a major operation. It's something I can take a look into, but I wanted to see what the thoughts are on this solution before investing the time.
Thanks!
> TS Definition Updates

- index.d.ts
Some interfaces are not exported in typescript type information file. This pull request will fix this problem.
> Export missed interfaces in index.d.ts

- README.md
- index.d.ts
- src/http-client.js
- test/auth.js
I have added description to the README file and a test. 
Test, though, I could not run - I have no OCO data in testing account.
> Adding allOrdersOCO endpoint

- index.d.ts
- src/websocket.js
I noticed that the "executionReport" event was missing some properties so I added them.
> feat(websocket): Extend execution report types

- README.md
- index.d.ts
- src/http-client.js
This option was missed, adding it will reduce request cost.
> Add symbol option to /ticker/price endpoint

- README.md
- index.d.ts
- src/http-client.js
- test/auth.js
Added Futures wallet balance functions and related types, test
> add REST endpoint for futures account balance

- index.d.ts
> fix: Add missing quoteQty field in TradeResult

- index.d.ts
- package.json
Added some margin methods to Binance interface:
- marginOrder
- marginAllOrders
- marginCancelOrder
- marginOpenOrders
> Added methods to Binance interface

- index.d.ts
Add some parameters to new order interface and SideEffectType
> Add some parameters to new order interface

- README.md
- index.d.ts
- src/http-client.js
Link for documentation
https://binance-docs.github.io/apidocs/spot/en/#query-isolated-margin-account-info-user_data
> Add Query Isolated Margin Account Info

- index.d.ts
futuresOpenOrders returns an array actually
> futuresOpenOrders returns an array actually

- README.md
- index.d.ts
- src/http-client.js
@balthazar hi it's me again.
I'm really sorry for the small iterations with each PR.
API docs - https://binance-docs.github.io/apidocs/spot/en/#query-max-borrow-user_data
> Add marginMaxBorrow

- README.md
- index.d.ts
- src/http-client.js
Hi @balthazar 
I added getInfo() types that were missed
Also, I added universalTransfer and universalTransferHistory endpoints
> getInfo() type and universalTransfer

- index.d.ts
Adding some types for futures functionality.
> Adding types for futures depth APIs

- README.md
- index.d.ts
- src/http-client.js
Hi @balthazar !
Another micro PR with 3 new margin methods.
Thanks for your patience!
> Add 3 margin methods

- index.d.ts
- src/http-client.js
@balthazar 
Hi. Sorry for micro PR again.
This variable is cursed for some reason and now I made a type in typings. Fixing it
> Typo in naming (again)

- index.d.ts
fixes the liquidation stream typings
> fix function type names

- index.d.ts
- src/websocket.js
This should fix the ACCOUNT_UPDATE event type from `futuresUser`
`client.ws.futuresUser((event) => 
{
if(event.eventType === "ACCOUNT_UPDATE") {
console.log(event)
}
}
);`
> add AccountUpdate type and fix mapping

- index.d.ts
I found out the margin trade history api are missing, I've added the interface, pleas check
> add margin myTrades query

- README.md
- index.d.ts
- src/http-client.js
`STOP_LOSS`, 'STOP_LOSS/TAKE_PROFIT_LIMIT` are returning `Invalid orderType` 
Updated those based on the binance docs.
> Update Stop orders and added `TRAILING_STOP_MARKET`

- index.d.ts
Related to:
Missing types for futures WS api #331
> Adding futuresAggTrades and changing from Trade to AggregatedTrade

- README.md
- src/http-client.js
https://binance-docs.github.io/apidocs/spot/en/#asset-detail-sapi-user_data
This can be useful to fetch deposit/withdrawal status and fees.
> Adds support for asset info

- index.d.ts
Fix #418
https://binance-docs.github.io/apidocs/futures/en/#change-initial-leverage-trade
> Stricter typings for margin type

- README.md
- index.d.ts
- src/http-client.js
Fix #416
https://binance-docs.github.io/apidocs/futures/en/#notional-and-leverage-brackets-user_data
> Add Notional and Leverage Brackets

- src/open-websocket.js
From https://github.com/Ashlar/binance-api-node/issues/404#issuecomment-833668033 solution
> Fix browser websocket error

- README.md
Fixes https://github.com/Ashlar/binance-api-node/issues/430.
A closing details tag was missing from the topic before.
> Fixes WebSockets section in README

- src/websocket.js
added balance change prop according to latest changelog:
https://binance-docs.github.io/apidocs/futures/en/#change-log
> add balanceChange to 'ACCOUNT_UPDATE' event

- README.md
- index.d.ts
- src/http-client.js
new version breaks TS code now, mainly restored the STOP_LOSS_LIMIT/TAKE_PROFIT_LIMIT support from PR: 
https://github.com/Ashlar/binance-api-node/pull/388
> Restored STOP_LOSS_LIMIT/TAKE_PROFIT_LIMIT support for TS

- index.d.ts
Links for references :
- https://binance-docs.github.io/apidocs/spot/en/#current-open-orders-user_data
- https://binance-docs.github.io/apidocs/spot/en/#all-orders-user_data
> Add openOrders and allOrders Typescript properties

- package.json
- yarn.lock
This fixes https://github.com/Ashlar/binance-api-node/issues/444
> Use node-fetch v2.6.1

- README.md
- index.d.ts
@balthazar hi. Long time no see.
I added typings for cross-margin account info. The method already implemented before.
Also, I added missed link for readme
> Typings for cross margin account info

- src/http-client.js
- Fixed missing arguments in futuresCancelAllOpenOrders
- Fixed typo in path of futuresCancelAllOpenOrders and futuresBatchOrders
> Fix for futuresCancelAllOpenOrders and futuresBatchOrders

- index.d.ts
I extended marginBorrow and marginRepay types.
Also, I fixed some styling issues like:
- add a trailing comma
- remove unnesecary commas and semicolons from interfaces
- quotes fix
> Change marginLoan and marginRepay types

- index.d.ts
Hi @balthazar.
Some small type
> add miniTickers type

- README.md
- src/http-client.js
hi here is a pull request to add dustLog (/sapi/v1/asset/dribblet) to the api
> added dustLog method

- index.d.ts
fixes issues described in #459
> fix undefined enums

- README.md
- index.d.ts
- src/http-client.js
Hello @balthazar 
I added one new method.
Also fixed some old types
> Add apiPermission method.

- src/websocket.js
Fixes the issues mentioned in #495.
> Handle closed user streams properly

- README.md
- index.d.ts
- src/http-client.js
I added a function named `marginOrderOco`. I tested it and it works properly.
> Add margin order oco

- index.d.ts
Hi @balthazar 
Quick fix for #502
> Change types for timeInForce

- src/websocket.js
This functionality allows developers to subscribe to socket open events for responding to intermittent connections with a customized logic.
Ex: The client may fail to receive an update from the server in cases of dropped connections; for this reason, this functionality is required to enable it to query the order statuses using the REST API after the socket connection is reestablished.
> Emit the open events from user data stream sockets

- README.md
- index.d.ts
- src/http-client.js
User can active or inactive margin isolated trading pair with this method.
> Make marginActiveAccount

- index.d.ts
- package.json
- src/http-client.js
- src/open-websocket.js
- src/websocket.js
- test/index.js
- yarn.lock
Hello, I add proxy support for http endpoints. Maybe we have some more to do for ws.
I add the typing for futuresCandles too, and add support for this 2 more methods:
- futuresMarkPriceCandles
- futuresIndexPriceCandles
> feat: add proxy

- src/websocket.js
> 🚑 fix: wrong order ids

- index.d.ts
- src/websocket.js
- test/index.js
- Fixed method interface (input parameters)
- Added method to WebSocket type
- Renamed method to match Doc (changed `allMiniTicker` to `allMiniTickers`
> Bug fix: Websockets allMiniTickers

- index.d.ts
- add interface NetworkInformation
- add interface CoinInformation
- edit capitalConfigs
- edit depositAddress
> Edit index.d.ts. add new interfaces and more params

- package.json
- test/index.js
> Fix audit errors

- README.md
In my previous PR I forgot to update README
> Updated README to reflect myTrades new parameters

- README.md
- index.d.ts
- src/http-client.js
Implemented this call: https://binance-docs.github.io/apidocs/spot/en/#portfolio-margin-endpoints
> Add getPortfolioMarginAccountInfo method.

- .gitignore
- index.d.ts
Update typings definition to include 'futuresAllOrders'.
> Add futuresAllOrders to type definitions

- .gitignore
- index.d.ts
Adds typing definition for `futuresAllOrders`
> add: futuresAllOrders to type definitions

- index.d.ts
fix the typo in index.d.ts file
> fix(index.d.ts): withdraw response typo

- index.d.ts
- package.json
- src/websocket.js
- test/index.js
added ws event list status (OCO event)
> add: ws user listStatus event

- src/http-client.js
I'm sorry, the previous pull request was not completely correct.
> Change responseHandler

- index.d.ts
This PR will add a few useful types to the Binance interface.
> More types

- index.d.ts
I just realized while I was working that the symbol interface is not complete, and I am sharing my changes in my local node_modules folder in order to keep everything working. This may be challenging for beginners.
> Fix Futures Symbol Interface 

- index.d.ts
Added typing for dust transfer method according to Binance API docs
> Typing for dust transfer (#631)
